{% set version = "1.1-12" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-automap
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/automap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/automap/automap_{{ version }}.tar.gz
  sha256: a5f4bb9c9940c5eba61fd54854cc42df094e29f51eff66d334ee0e429405e6d3

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2
    - r-gstat
    - r-lattice
    - r-reshape
    - r-sf
    - r-sp
    - r-stars
  run:
    - r-base
    - r-ggplot2
    - r-gstat
    - r-lattice
    - r-reshape
    - r-sf
    - r-sp
    - r-stars

test:
  commands:
    - $R -e "library('automap')"           # [not win]
    - "\"%R%\" -e \"library('automap')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=automap
  license: GPL-2.0-or-later
  summary: This package performs an automatic interpolation by automatically estimating the variogram and then calling gstat.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - daf
