travis:
  secure:
    BINSTAR_TOKEN: IxjZKh3dpLbtsS86a/y/5TqYB+r2IoORJhPlXDKBKcBTCL2wV30jjKto3GY+AgA+qgWULwddUwyFmkZnbcduWM2wrvY29M1NXAXdPsp/eEi5vkvt7dxjFFG+26uaYJuknPaxTESkjmztdrbGu3/iyBRxitATcVDMf6XfwIDnq/KEj6fK87EWK0MbX09kMWt1dxGwm8P/fsTsMEMoc28fubWIuPoxRXkiJV/thdnA4OC8Bwunj3rMxuwp4zK66PLY57+i33EzTUAqgtrOJSAoF7hQG0tzTUxPnv9rb2ZZgHKtnNT5nWzwomFvvQks80ISKYH0RfOncz5bqrCSia+HjDGcvDbbyEiECKS7qjFWEBJEHcPeLbXkHV+kdQ/l4Keu07uhvWAbwILOfS5xADQgsytWKHH5Uhq+BCkCTQzUBUZGbcaDHzvax1Fl8bpE5lwPAcAUyNZJ2jN7nhgNfqF4DroYm+9JGxNv9apHsT02+rxZx/f1IKhh91hTfWwiQnZhXpYruK2uSXDgQmWyeMTaeC232vgf9oPKCk2CdFPaUU9SL1Mn11MRDN10yveO2fOXhotpaPeF6wrERXq7Ml8NSbTQhKI6Aq3g57Fe8AZI/OAgrTkSkXPm5wSF7miWd4A+6/9ibkv16KudNO40Vias60OIpNKf5KZeTcJ2oNlgFk0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
