appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: jyOyGgISh+1sSvnPA2cWPUYmF9ag1wqtJfRDX9qyodqmlB9DqHVhxliR6bxa2qmxGadDAMuI2DUbhod3C7PkMgQeWPY52YkaJZ4TyDHz+o4zyJM1Rr0OPBOtDjCWCIGmfKhUY3FSQh2i3UKX9EwAQWm5wg5KVj4CiBrmgqMWZrWbQKzyYZtPwUQyz9Dt7pRsaP1mqwm3ohrRBQjA2ktfMjnH1Nq/Picgu2SKInLdZdpppQwcmddzpAv6mfOMBQxVO4LBJVWCowyd+bs4uY1goRbxIENzjyCHOo99S/7mlmuDjxfdslpQnSWk33oxSRaQBYtj0gSAOij3fRxAcC5PR1p9IKoWUOzMfuKcNnZXmK0DsVz2YsmY+vknT1RqKJozpNtCdaxSJUYYE5WDjpQP7+td0NxD0KgYPNq1K3/vM93RCI8PJaVmlwNssgiHIRgLysSwnuFBx2AwlXgrjnGpstFp37Z6DYwiEt4+CUrSW812InYYGaJzvrTeK3QDUBuApU0VPrKRTwugaHV8VcGCUPl2f6G1DQhHl402NAJ1NB0q/6/0RbNUQFKBWmvf/OoqQpa8m7lUcsbIWY9owX6R5Zv1WKdZhDxBrwShdFBNYUBePf0dtIi+DSiIUEqO9v6b+3q8fx5M/46SIzDBkc89qdHNFVzTnLEVHqSfgNS3czM=}
